import { useState, useEffect } from "react";
import axios from "axios";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";

import jsPDF from "jspdf";

function Reports() {
  const [report, setReport] = useState({
    employees: 0,
    attendance: 0,
    inventory: 0,
    production: 0,
    sales: 0,
    revenue: 0,
  });

  useEffect(() => {
    fetchReport();
  }, []);

  const fetchReport = async () => {
    try {
      const res = await axios.get(
        "https://producttrack-backend-5wd3.onrender.com/api/reports/dashboard"
      );

      setReport(res.data);
    } catch (error) {
      console.log(error);
    }
  };

  const chartData = [
    {
      name: "Employees",
      value: report.employees,
    },
    {
      name: "Attendance",
      value: report.attendance,
    },
    {
      name: "Inventory",
      value: report.inventory,
    },
    {
      name: "Production",
      value: report.production,
    },
    {
      name: "Sales",
      value: report.sales,
    },
  ];

  const COLORS = [
    "#2563eb",
    "#16a34a",
    "#eab308",
    "#9333ea",
    "#dc2626",
  ];

  const generateReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text(
      "ProductTrack Pro Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Report Date: ${new Date().toLocaleDateString()}`,
      20,
      40
    );

    doc.text(
      `Total Employees: ${report.employees}`,
      20,
      60
    );

    doc.text(
      `Attendance Records: ${report.attendance}`,
      20,
      80
    );

    doc.text(
      `Inventory Items: ${report.inventory}`,
      20,
      100
    );

    doc.text(
      `Production Records: ${report.production}`,
      20,
      120
    );

    doc.text(
      `Sales Orders: ${report.sales}`,
      20,
      140
    );

    doc.text(
      `Total Revenue: ₹${report.revenue}`,
      20,
      160
    );

    doc.text(
      "Generated By ProductTrack Pro",
      20,
      190
    );

    doc.save("Company_Report.pdf");
  };

  return (
    <div className="p-10 bg-gradient-to-br from-slate-100 to-slate-200 min-h-screen">
    

      <h1 className="text-5xl font-extrabold text-slate-800 mb-2">
        Reports & Analytics
      </h1>

      <div className="bg-white p-4 rounded-xl shadow-md mb-8">
        <p className="text-lg font-semibold text-gray-700">
          📅 Report Date :
          <span className="text-blue-700 ml-2">
            {new Date().toLocaleDateString()}
          </span>
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-6 mb-8">

        <div className="bg-blue-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Employees</h3>
          <p className="text-3xl font-bold">
            {report.employees}
          </p>
        </div>

        <div className="bg-green-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Attendance</h3>
          <p className="text-3xl font-bold">
            {report.attendance}
          </p>
        </div>

        <div className="bg-yellow-500 text-white p-5 rounded-xl shadow-lg">
          <h3>Inventory</h3>
          <p className="text-3xl font-bold">
            {report.inventory}
          </p>
        </div>

        <div className="bg-purple-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Production</h3>
          <p className="text-3xl font-bold">
            {report.production}
          </p>
        </div>

        <div className="bg-red-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Revenue</h3>
          <p className="text-3xl font-bold">
            ₹{report.revenue}
          </p>
        </div>

      </div>

      {/* Summary */}
      <div className="bg-white p-8 rounded-xl shadow-lg mb-8">

        <h2 className="text-2xl font-bold mb-6">
          Company Summary Report
        </h2>

        <div className="space-y-4 text-lg">

          <div className="flex justify-between border-b pb-2">
            <span>👥 Total Employees</span>
            <strong>{report.employees}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>📅 Attendance Records</span>
            <strong>{report.attendance}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>📦 Inventory Items</span>
            <strong>{report.inventory}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>🏭 Production Records</span>
            <strong>{report.production}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>🛒 Sales Orders</span>
            <strong>{report.sales}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>💰 Total Revenue</span>
            <strong>₹{report.revenue}</strong>
          </div>

        </div>

      </div>

      {/* Charts */}
      <div className="grid md:grid-cols-2 gap-8">

        <div className="bg-white p-6 rounded-xl shadow-lg">

          <h2 className="text-2xl font-extrabold text-blue-700 mb-5">
            📈 Company Statistics
          </h2>

          <ResponsiveContainer
            width="100%"
            height={300}
          >
            <BarChart data={chartData}>
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />

              <Bar
                dataKey="value"
                fill="#2563eb"
                radius={[10, 10, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>

        </div>

        <div className="bg-white p-6 rounded-xl shadow-lg">

          <h2 className="text-2xl font-extrabold text-purple-700 mb-5">
            🥧 Data Distribution
          </h2>

          <ResponsiveContainer
            width="100%"
            height={300}
          >
            <PieChart>

              <Pie
                data={chartData}
                dataKey="value"
                nameKey="name"
                outerRadius={100}
                label
              >
                {chartData.map(
                  (entry, index) => (
                    <Cell
                      key={index}
                      fill={
                        COLORS[
                          index % COLORS.length
                        ]
                      }
                    />
                  )
                )}
              </Pie>

              <Tooltip />

            </PieChart>
          </ResponsiveContainer>

        </div>

      </div>

      {/* Remarks */}
      <div className="bg-white p-8 rounded-xl shadow-lg mt-8">

        <h2 className="text-2xl font-bold mb-4">
          Report Remarks
        </h2>

        <ul className="list-disc ml-6 space-y-2">

          <li>
            Employee data is tracked in
            real-time.
          </li>

          <li>
            Attendance records are maintained
            daily.
          </li>

          <li>
            Inventory stock levels are
            monitored continuously.
          </li>

          <li>
            Production progress is recorded.
          </li>

          <li>
            Revenue is calculated from all
            sales orders.
          </li>

        </ul>

        <button
          onClick={generateReport}
          className="mt-8 bg-gradient-to-r from-blue-700 to-indigo-800 hover:scale-105 transition-all duration-300 text-white px-8 py-4 rounded-xl font-bold shadow-lg"
        >
          Download PDF Report
        </button>

      </div>

    </div>
  );
}

export default Reports;