import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";

import jsPDF from "jspdf";

function Reports() {
  const employees =
    JSON.parse(localStorage.getItem("employees")) || [];

  const attendance =
    JSON.parse(localStorage.getItem("attendance")) || [];

  const inventory =
    JSON.parse(localStorage.getItem("inventory")) || [];

  const production =
    JSON.parse(localStorage.getItem("production")) || [];

  const sales =
    JSON.parse(localStorage.getItem("sales")) || [];

  const revenue = sales.reduce(
    (sum, order) => sum + Number(order.amount || 0),
    0
  );

  const chartData = [
    {
      name: "Employees",
      value: employees.length,
    },
    {
      name: "Attendance",
      value: attendance.length,
    },
    {
      name: "Inventory",
      value: inventory.length,
    },
    {
      name: "Production",
      value: production.length,
    },
    {
      name: "Sales",
      value: sales.length,
    },
  ];

  const COLORS = [
    "#2563eb",
    "#16a34a",
    "#eab308",
    "#9333ea",
    "#dc2626",
  ];

  const generateReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text(
      "ProductTrack Pro Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Report Date: ${new Date().toLocaleDateString()}`,
      20,
      40
    );

    doc.text(
      `Total Employees: ${employees.length}`,
      20,
      60
    );

    doc.text(
      `Attendance Records: ${attendance.length}`,
      20,
      80
    );

    doc.text(
      `Inventory Items: ${inventory.length}`,
      20,
      100
    );

    doc.text(
      `Production Records: ${production.length}`,
      20,
      120
    );

    doc.text(
      `Sales Orders: ${sales.length}`,
      20,
      140
    );

    doc.text(
      `Total Revenue: ₹${revenue}`,
      20,
      160
    );

    doc.text(
      "Generated By ProductTrack Pro",
      20,
      190
    );

    doc.save("Company_Report.pdf");
  };

  return (
    <div className="p-10 bg-slate-100 min-h-screen">

      <h1 className="text-4xl font-bold mb-4">
        Reports & Analytics
      </h1>

      <p className="text-gray-600 mb-8">
        Report Date :
        {" "}
        {new Date().toLocaleDateString()}
      </p>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-6 mb-8">

        <div className="bg-blue-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Employees</h3>
          <p className="text-3xl font-bold">
            {employees.length}
          </p>
        </div>

        <div className="bg-green-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Attendance</h3>
          <p className="text-3xl font-bold">
            {attendance.length}
          </p>
        </div>

        <div className="bg-yellow-500 text-white p-5 rounded-xl shadow-lg">
          <h3>Inventory</h3>
          <p className="text-3xl font-bold">
            {inventory.length}
          </p>
        </div>

        <div className="bg-purple-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Production</h3>
          <p className="text-3xl font-bold">
            {production.length}
          </p>
        </div>

        <div className="bg-red-600 text-white p-5 rounded-xl shadow-lg">
          <h3>Revenue</h3>
          <p className="text-3xl font-bold">
            ₹{revenue}
          </p>
        </div>

      </div>

      {/* Company Summary */}
      <div className="bg-white p-8 rounded-xl shadow-lg mb-8">

        <h2 className="text-2xl font-bold mb-6">
          Company Summary Report
        </h2>

        <div className="space-y-4 text-lg">

          <div className="flex justify-between border-b pb-2">
            <span>👥 Total Employees</span>
            <strong>{employees.length}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>📅 Attendance Records</span>
            <strong>{attendance.length}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>📦 Inventory Items</span>
            <strong>{inventory.length}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>🏭 Production Records</span>
            <strong>{production.length}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>🛒 Sales Orders</span>
            <strong>{sales.length}</strong>
          </div>

          <div className="flex justify-between border-b pb-2">
            <span>💰 Total Revenue</span>
            <strong>₹{revenue}</strong>
          </div>

        </div>

      </div>

      {/* Charts */}
      <div className="grid md:grid-cols-2 gap-8">

        <div className="bg-white p-6 rounded-xl shadow-lg">

          <h2 className="text-2xl font-bold mb-5">
            Company Statistics
          </h2>

          <ResponsiveContainer
            width="100%"
            height={300}
          >
            <BarChart data={chartData}>
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />

              <Bar
                dataKey="value"
                fill="#2563eb"
                radius={[10, 10, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>

        </div>

        <div className="bg-white p-6 rounded-xl shadow-lg">

          <h2 className="text-2xl font-bold mb-5">
            Data Distribution
          </h2>

          <ResponsiveContainer
            width="100%"
            height={300}
          >
            <PieChart>

              <Pie
                data={chartData}
                dataKey="value"
                nameKey="name"
                outerRadius={100}
                label
              >
                {chartData.map(
                  (entry, index) => (
                    <Cell
                      key={index}
                      fill={
                        COLORS[
                          index % COLORS.length
                        ]
                      }
                    />
                  )
                )}
              </Pie>

              <Tooltip />

            </PieChart>
          </ResponsiveContainer>

        </div>

      </div>

      {/* Remarks */}
      <div className="bg-white p-8 rounded-xl shadow-lg mt-8">

        <h2 className="text-2xl font-bold mb-4">
          Report Remarks
        </h2>

        <ul className="list-disc ml-6 space-y-2">

          <li>
            Employee data is tracked in
            real-time.
          </li>

          <li>
            Attendance records are maintained
            daily.
          </li>

          <li>
            Inventory stock levels are
            monitored continuously.
          </li>

          <li>
            Production progress is recorded.
          </li>

          <li>
            Revenue is calculated from all
            sales orders.
          </li>

        </ul>

        <button
          onClick={generateReport}
          className="mt-8 bg-blue-700 hover:bg-blue-800 text-white px-6 py-3 rounded-lg"
        >
          Download PDF Report
        </button>

      </div>

    </div>
  );
}

export default Reports;